# Generated by Django 3.2.9 on 2021-11-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstAPI', '0002_rename_employee_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
