# Generated by Django 3.2.9 on 2021-11-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstAPI', '0003_rename_employees_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
